### ISSUE TITLE
Probably doing something wrong but I'm getting mixed 64 and 32 bit binaries on linux.

### ISSUE THREAD

**Issue by hanetzer** [smx-smx/ASMTool#10]
So. The x370 chipset on ryzen is very much like asmedia stuff, and was hoping to poke it a bit in order to assist my port of coreboot to 'Asrock X370 Killer Sli/AC' (kind of in a working state; more to be done).

By issuing `dotnet build` I get a 64-bit ELF for AsmTool but the dlls come out as 32 bit. Attempting to run AsmTool
nets me the following error:
```
Unhandled exception. System.BadImageFormatException: Could not load file or assembly '~/ASMTool/AsmTool/bin/Debug/net6.0/AsmTool.dll'. An attempt was made to load a program with
an incorrect format.

File name: '~/ASMTool/AsmTool/bin/Debug/net6.0/AsmTool.dll'
Aborted (core dumped)
```
libAsmIOLinux.so is compiled and in the directory next to AsmTool (it is also a 64-bit ELF)

**Comment by rhn** [comment]
I have the same issue. I used the CI dockerfile and commands, but the created artifact is unuseable.

**Comment by voltagex** [comment]
In the CMake files, there's a line that clears the target platform but it doesn't get set again on Linux.

Theoretically 

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 4da64d4..1787fce 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -20,6 +20,7 @@ ADD_DOTNET(${CMAKE_SOURCE_DIR}/AsmTool.sln
 )

 if(UNIX)
+       set(target_platform PLATFORM x64)
        enable_language(C)
        add_subdirectory(AsmTool/Linux)
        add_dependencies(AsmTool_sln asmIoLinux)
```
should be enough to fix it, but 

```
voltagex@BeeMovie:~/src/ASMTool/build/out$ file libasmIoLinux.so
libasmIoLinux.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=16e6d63384efb4239eb312f502242296346eae03, not stripped
voltagex@BeeMovie:~/src/ASMTool/build/out$ file AsmTool
AsmTool: ELF 64-bit LSB pie executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=10540531054f88680224e7bf543dc2dbef55c014, for GNU/Linux 2.6.32, stripped
voltagex@BeeMovie:~/src/ASMTool/build/out$ file AsmTool.dll
AsmTool.dll: PE32 executable (console) Intel 80386 Mono/.Net assembly, for MS Windows, 3 sections
```

@smx any idea what's going on here?

**Comment by vrbadev** [comment]
I have the same problem, any idea how to compile it properly on Linux?

**Comment by vadim-ktnkv** [comment]
Compiled it with corrected `<PlatformTarget>x64</PlatformTarget>`, copied libasmIoLinux.so along with ASMTool, when trying to run, got this:
`
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'AsmIOLinux.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libAsmIOLinux.so: cannot open shared object file: No such file or directory
   at AsmTool.LinuxNativeIO.LoadAsmIODriver()
   at AsmTool.LinuxAsmIO.LoadAsmIODriver() in /home/x/test/ASMTool/AsmTool/LinuxAsmIO.cs:line 44
   at AsmTool.Program.Main(String[] args) in /home/x/test/ASMTool/AsmTool/Program.cs:line 26
[1]    4004642 IOT instruction (core dumped)  ./AsmTool
`

**Comment by smx-smx** [comment]
The problem is the following: 
On Windows, we interoperate with ASMedia DLLs (which are 32bit). That's why I had switched the .NET project to 
```xml
<PlatformTarget>x86</PlatformTarget>
```

On Linux we don't have this limitation (since we're using my `asmIoLinux` reimplementation).
The fix would be to force 32bit only on Windows, while keeping it unset on Linux (so it picks whatever the host has)
