### ISSUE TITLE
Cannot compile under Linux (undefined reference to `main')

### ISSUE THREAD

**Issue by isopix** [smx-smx/ASMTool#2]
After typing command from Readme.md, I'm getting such error (I guess it's maybe supposed to be used only as library, right?

gcc -fPIC -Ofast Linux/AsmIOLinux.c -o libAsmIOLinux.so
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.1/../../../../lib/Scrt1.o: in function `_start':
(.text+0x24): undefined reference to `main'
collect2: error: ld returned 1 exit status

BTW, I do wonder If I could use this tool to flash ASMT-1051, that has been unsuccesfully flashed by incorrect firmware (151030_B1_0B_01.bi from 105MPTools_v2.2.0.0.rar, that somebody posted as correct firmware for it on usbdev.ru)
I still got correct firmware that worked on it before, but ASMedia MPTool(or other windows tools) doesn't detect it now as ASMT-1051

I'm attaching lsusb and kernel logs, before I wrote any firmware to it:

174c:1153 ASMedia Technology Inc. ASM1153 SATA 3Gb/s bridge

[102714.433596] usb 3-1: new SuperSpeed Gen 1 USB device number 5 using xhci_hcd
[102714.446109] usb 3-1: New USB device found, idVendor=174c, idProduct=55aa, bcdDevice= 1.00
[102714.446114] usb 3-1: New USB device strings: Mfr=2, Product=3, SerialNumber=1
[102714.446117] usb 3-1: Product: ASMT1051
[102714.446119] usb 3-1: Manufacturer: asmedia
[102714.446120] usb 3-1: SerialNumber: 12345678BDFC
[103611.625111] usb 3-1: USB disconnect, device number 5
[103833.565577] usb 3-1: new SuperSpeed Gen 1 USB device number 6 using xhci_hcd
[103833.578355] usb 3-1: New USB device found, idVendor=174c, idProduct=1153, bcdDevice= 0.01
[103833.578358] usb 3-1: New USB device strings: Mfr=2, Product=3, SerialNumber=1
[103833.578360] usb 3-1: Product: AS2115
[103833.578361] usb 3-1: Manufacturer: ASMedia
[103833.578362] usb 3-1: SerialNumber: 00000000000000000000

**Comment by hartimcwildfly** [comment]
The command is wrong. The correct one for linux is: `gcc -shared -o libAsmIOLinux.so -fPIC Linux/AsmIOLinux.c`

**Comment by isopix** [comment]
OK, it compiles now. But why not fix README.md instead of giving me information how to fix it.
```
Linux
gcc -fPIC -Ofast Linux/AsmIOLinux.c -o libAsmIOLinux.so Place the resulting .so file next to the ASMTool executable (obtained by building this project)
```
And stil I do wonder how to compile "ASMTool" executable (mentioned above in README.md)? Or maybe this information is also incorrect and it's only library for now?

**Comment by hartimcwildfly** [comment]
I didn't know either. I ported it to .NET 5 which is easier to handle on linux. See my forked project. I'm now able to build the project and the lib is loaded at the start. But the applications exits because of a memory fault. With this you only need to run `dotnet build` and place the libAsmIOLinux.so into folder ./bin/Debug/net5.0 then you can run ./bin/Debug/net5.0/AsmTool

**Comment by hartimcwildfly** [comment]
Let me know if I could help you.

**Comment by hartimcwildfly** [comment]
The project itself can be compiled under Linux with Jetbrains Rider, under Windows with Visual Studio or on both platform with the above mentioned `dotnet build` command when you have installed the .NET 5 SDK. The gcc command is only for compiling the linux specific library which is loaded by the AsmTool.

**Comment by hartimcwildfly** [comment]
I analyzed the AsmIOLinux.c a little bit. It seems like the return values of the methods at initialization are not checked and thus the method call when reading fails with a segfault. I started to implement a more reliable version of this, but it's a lot of work. So at the moment better use the Windows version.

**Comment by isopix** [comment]
Thanks for all the help. BTW, do you know if I can use this tool to
flash the chip if it's not opening the port, so official Windows
software cannot see it? (I flashed bad firmware). Because otherwise it
would be useless for me anyway.

**Comment by hartimcwildfly** [comment]
Only the read functions are currently fully implemented. But it shouldn't be that hard to extend it with a write function. My main problem at the moment is the communication in general.

**Comment by smx-smx** [comment]
Sorry, I didn't get notified about this issue and I missed the discussion.
Yes, it's supposed to be a shared library only and you need to run the dotnet binary as root.
Strange that it segfaults, I could give it another check on my machine

**Comment by smx-smx** [comment]
As about the original issue, this tool was originally written for PCI based chips, not USB.
It surely won't work out of the box without writing ad-hoc USB code, and I don't have any ASMedia USB bridge chip with me at this time

**Comment by isopix** [comment]
Are you sure about not having one?

Most of "USB Sata cables/adapter" and  usb SATA/mSATA enclosures got
ASMedia chipset inside. Another thing if it's worth the effort ;-)

**Comment by smx-smx** [comment]
I'm pretty sure i only have JMicrons, maybe one is USBest iirc

**Comment by ofl1** [comment]
Hi @isopix 
here is a version of the Linux file that compiles and works for me. I inserted the main and other necessary functions. With it I dumped the firmware of the ASM1042 in an ExpressCard. No other tool was able to do this. Before the compilation you have to enter the size of the firmware (64k/128k) and bus/device/function (from line 195).

Now the big question for everyone is: How can you expand it so that you can flash new firmware? Are there any ideas or research results?

[AsmIOLinux.zip](https://github.com/smx-smx/ASMTool/files/6111901/AsmIOLinux.zip)

**Comment by smx-smx** [comment]
@ofl1 nice, thanks for sharing your version.
Is there any important change from the version in master besides the conversion to C-only?

Note that the linux backend was designed to be used from C#, that's why it's a shared library

**Comment by ofl1** [comment]
@smx-smx you are welcome. I didn't change anything on the old Linux backend, just added code. Omitted the controller's automatic search.

Your statements regarding writing the firmware sound like it is theoretically clear how to do it. There is great interest in such a possibility, because other tools do not work with certain ASM versions or SPI-ROMs. 

My SPI-ROM was a P25D40H. I tried to expand your tool and experimented with SPIWrite without success. The content of the SPI-ROM was somehow overwritten, because when reading back afterwards only scrap arrived. Strangely, the controller still worked, just as good or bad as before. I also tried a programmer with clamp.

It is better to do the experiments with an ExpressCard than with chips on the mainboard, and to have a small supply of ExpressCards. For me, however, the issue has settled because I bought an ExpressCard with a different controller that works perfectly.

**Comment by isopix** [comment]
That's super. As I've paid $2(SanDisk, open box) for this adapter,
it's not a big loss (and will not be if it will get otally broken,
because COM port  doesn't work alrady).

But it would be huge win for owners of pricier adapter with similar chip.

but as I stated before, you can see it in device manager, but you
cannot use it, nor flash another firmware(com port doesn't appear)

**Comment by maenpaa24** [comment]
Hi everyone, I have been tinkering with this code and would like to share my experience and ask a few questions if possible. The first one is that none of the following codes writes anything to the chip, right? They only read, which should be safe, am I wrong? 

Other than that, I can not build @smx-smx’s code in linux because I can not install any version of .net 4. However, I can build it in windows. It does not detect the asmedia chip and the output is: “bus:F3, dev:1B, func:3 => FFFFFFFF” where bus goes from 00 to FF in a loop, dev: changes a little and function changes between a few numbers like 4,5,6,7.

 On the other hand, I can build @hartimcwildfly’s code both on windows and linux. On windows it gives the following error:

```
Unloading ASM Driver...
Unhandled exception. System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (0x8007000B)
   at AsmTool.AsmIODll.UnloadAsmIODriver()
   at AsmTool.WindowsAsmIO.UnloadAsmIODriver() in C:\Users\User\ASMTool\AsmTool\WindowsAsmIO.cs:line 99
   at AsmTool.Program.Main(String[] args) in C:\Users\User\ASMTool\AsmTool\Program.cs:line 24
```

whereas in linux the output is similar to that of hartimcwildfly’s code in windows but it ends at bus:FF with the following output:

```
bus:FF, dev:1F, func:7 => FFFFFFFF
Unhandled exception. System.Exception: No ASMedia device detected!
   at AsmTool.AsmDevice..ctor(IAsmIO io) in /home/user/ASMTool_net5/AsmTool/AsmDevice.cs:line 43
   at AsmTool.Program.Main(String[] args) in /home/user/ASMTool_net5/AsmTool/Program.cs:line 32
Aborted
```

Regarding @ofl1’s code, I can build it and it seems to work. However, in order to avoid bricking or any other issue, I have some questions that I would like to ask before experimenting any further.

1.- I wonder if the size of the firmware must be exact? Is there any problem if the size you set is greater or smaller than the actual size?
2.- In case someone mistakenly writes a wrong value for the pci bus in the code, what may be the consequences? I guess as the code only reads memory, it should be safe, right?

**Comment by t0niX** [comment]
Hello all,

could somebody please help me out @hartimcwildfly, @smx-smx?

As I mistakenly flashed a wrong firmware to my ASM 3074 (I used one for an ASM 3142 as I thought that’s the chip on my motherboard; It still works though) I would like to re-flash the original firmware. Sadly it’s not available publicly

The good thing is: My motherboard has two ASM 3074 controllers of which one was deactivated during the flash so it still has the original firmware on it. This is the one I would like to dump the firmware from.

I am not a coder which is why I don’t have any tools to build myself a binary of your repo. Nevertheless I am trying my best and installed Visual Studio Code to build the version @hartimcwildfly provided. Anyways: It doesn't work because I don't have "libAsmIOLinux.so" available (I believe).

**Would you be so kind to either compile a version for windows for me and share it or give me some support so I can build itr myself? 

Can I re-flash the extracted firmware 1:1 or do I need to edit the file using a hex editor?**

Thank you!!

**Comment by smx-smx** [comment]
> Would you be so kind to either compile a version for windows for me and share it or give me some support so I can build itr myself?

You can now download the latest build from Cirrus CI, as i just added build instructions with artifacts upload.
You can otherwise follow along https://github.com/smx-smx/ASMTool/blob/5bf8f1eb1041c7f4a6c79b952db8ab1143cab0de/.cirrus.yml to see how to replicate the build yourself
