### ISSUE TITLE
Does this work with asm1153e ?

### ISSUE THREAD

**Issue by Jack154nsk** [smx-smx/ASMTool#4]
Just wondering if this works with Asmedia asm1153e chip?

**Comment by smx-smx** [comment]
I cannot say for sure, as I don't have a device to test.
There is a success report for ASM1042 here: https://github.com/smx-smx/ASMTool/issues/2#issuecomment-794581063

**Comment by TCB13** [comment]
I was also trying with that chip, doesn't seem to detect it:

Unhandled exception. System.Exception: No ASMedia device detected!
   at AsmTool.AsmDevice..ctor(IAsmIO io) in C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\AsmTool\AsmDevice.cs:line 43
   at AsmTool.Program.Main(String[] args) in C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\AsmTool\Program.cs:line 31

However the official tool show it correctly:

![Image](https://github.com/user-attachments/assets/683aecca-bc21-4c7a-846f-63efa71e267b)

Maybe the problem is by AsmIo.sys AsmIo64.sys and asmiodll.dll files, but I can't find anything specific for this chip.
