### ISSUE TITLE
ASM1166 Support

### ISSUE THREAD

**Issue by Shonk** [smx-smx/ASMTool#9]
Any chance of adding support for Asmedia Sata controllers
I have a card with much newer firmware than my other two
and would really like to be able to dump it

Unhandled exception. System.Exception: No ASMedia device detected!
   at AsmTool.AsmDevice..ctor(IAsmIO io) in C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\AsmTool\AsmDevice.cs:line 43
   at AsmTool.Program.Main(String[] args) in C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\AsmTool\Program.cs:line 31

[https://i.postimg.cc/dJKKJM5x/Untitled.png](url)

**Comment by DeathStalker77** [comment]
Yes, that would be VERY nice!  I'm getting this ASM1166 M2 Adapter -

[https://www.amazon.com/Adapter-SATA3-0-NO-Riad-Desktop-Support/dp/B0B5RJHYFD](url)

And would like to ensure I have the most appropriate firmware for it.

Thanks!!!

--- DS

**Comment by galmok** [comment]
You are getting further than I am:

```
 Directory of C:\Temp\ASM1166\dump

20-08-2026  19:47    <DIR>          .
20-08-2026  19:42    <DIR>          ..
11-06-2015  11:57            19.920 AsmIo.sys_
11-06-2015  11:57            20.456 AsmIo64.sys
09-10-2014  15:56            72.920 asmiodll.dll
20-08-2026  19:42               998 AsmTool.deps.json
20-08-2026  19:42            22.016 AsmTool.dll
20-08-2026  19:42               184 AsmTool.dll.config
20-08-2026  19:42           117.760 AsmTool.exe
20-08-2026  19:42            17.900 AsmTool.pdb
20-08-2026  19:42               147 AsmTool.runtimeconfig.json
20-08-2026  19:42            19.456 Smx.SharpIO.dll
              10 File(s)        291.757 bytes
               2 Dir(s)  2.685.290.020.864 bytes free

C:\Temp\ASM1166\dump>asmtool
Unloading ASM Driver...
Loading ASM Driver...
Failed to load ASM IO Driver
```

I wonder which files you have...

If I could get it to run as much as you have, I might be able to find a way to make it work on the ASM1166.

**Comment by galmok** [comment]
I forked this project and added SATA support. Find it here: https://github.com/galmok/ASMTool
